/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class personal_nfl_opencv_demo_util_OpenCVHelper */

#ifndef _Included_personal_nfl_opencv_demo_util_OpenCVHelper
#define _Included_personal_nfl_opencv_demo_util_OpenCVHelper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     personal_nfl_opencv_demo_util_OpenCVHelper
 * Method:    gray
 * Signature: ([III)[I
 */
JNIEXPORT jintArray JNICALL Java_personal_nfl_opencv_demo_util_OpenCVHelper_gray
  (JNIEnv *, jclass, jintArray, jint, jint);

/*
 * Class:     personal_nfl_opencv_demo_util_OpenCVHelper
 * Method:    imageToGray
 * Signature: (Ljava/lang/String;)[I
 */
JNIEXPORT jintArray JNICALL Java_personal_nfl_opencv_demo_util_OpenCVHelper_imageToGray
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
